### ISSUE TITLE
Add return types to MainButton

### ISSUE THREAD

**Issue by vladimirkiva** [prKassad/telegram-webapps-types#1]
According to the documentation (https://core.telegram.org/bots/webapps#mainbutton)

> All these methods return the MainButton object so they can be chained.

**Comment by prKassad** [comment]
> According to the documentation (https://core.telegram.org/bots/webapps#mainbutton)
> 
> > All these methods return the MainButton object so they can be chained.

Vladimir, thank you for your report. Fixed in v1.0.5
